#ifndef MESSAGE_NO_H
#define MESSAGE_NO_H

#define MESSAGE_CODE_ORDER_ENTRY_REQUEST            1001
#define MESSAGE_CODE_ORDER_ENTRY_RESPONSE           1002
#define MESSAGE_CODE_ORDER_FETCH_REQUEST            1003
#define MESSAGE_CODE_ORDER_FETCH_RESPONSE           1004
#define MESSAGE_CODE_ORDER_MOD_REQUEST              1005
#define MESSAGE_CODE_ORDER_MOD_RESPONSE             1006
#define MESSAGE_CODE_ORDER_ORDERBOOK_FETCH_REQUEST  1007
#define MESSAGE_CODE_ORDER_ORDERBOOK_FETCH_RESPONSE 1008
#define MESSAGE_CODE_ORDER_TRADE_RESPONSE           3002


#endif
